[package]
name = "day_timer"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
winit = "0.28"
winapi = { version = "0.3.9", features = ["winuser", "wincon"] }

[profile.release]
lto = true

